### ISSUE TITLE
Minor suggestion

### ISSUE THREAD

**Issue by mntan3** [guzhaoyuan/drake-tutorial#2]
https://drake.guzhaoyuan.com/q-and-a/faq

If you are a robotics control ~~guy~~ person, drake is for you. Drake has a dedicated team working on multibody dynamics, planning and control. Drake has a whole bunch of tools that help ease the development of robot control.

**Comment by guzhaoyuan** [comment]
Thanks. Changed with 4450f0db3bd5c5d573e508c7fb61712e50508d48.
