### ISSUE TITLE
`Visualize data in LCM` How to see the trajectories?

### ISSUE THREAD

**Issue by zapplelove** [guzhaoyuan/drake-tutorial#5]
In [Visualize data in LCM](https://gblobscdn.gitbook.com/assets%2F-LgYfwVg89cfloOSocyC%2F-LhJQm219Jka_jubcY86%2F-LhJQsQLlSIty5iywZxX%2FUntitled.gif?alt=media&token=c343b42a-5927-48c9-981b-b2074ae3da56), I can see a window that contains trajectories, how to turn this option on?
I wish you can supplement more tutorials and I think it's difficult to learn drake.
thks!

**Comment by zapplelove** [comment]
> I wish you can supplement more tutorials and I think it's difficult to learn drake.
> thks!

**Comment by guzhaoyuan** [comment]
It's a function inside of the `drake-lcm-spy`. You just need to double click the LCM channel that you want to visualize, a window will pop up to visualize the LCM data history (the trajectory of data).
Here in the gif, I opened up the `IIWS_STATUS` channel.
Hope this helps.
