### ISSUE TITLE
failure to build

### ISSUE THREAD

**Issue by HaberR** [guzhaoyuan/drake-tutorial#6]
`bazel build //`
didn't work for me. Even
`bazel build //manipulation/util:geometry_inspector`
was causing my machine to crash. Ultimately I found [this post](https://github.com/bazelbuild/bazel/issues/1160) and tried 
`bazel build --jobs=2 //manipulation/util:geometry_inspector`
which worked. If I am not the only one who's running into this, it might be worth mentioning in the tutorial.

**Comment by guzhaoyuan** [comment]
Thanks for mentioning it!
This is because `bazel build ///` tries to use all available resources {CPU\ram} to compile and it can easily take up all the memory and causing the compilation failure.
