### ISSUE TITLE
Error in hello example.

### ISSUE THREAD

**Issue by wongearth** [guzhaoyuan/drake-tutorial#7]
Hello. I have been following your tutorial on page https://drake.guzhaoyuan.com/thing-to-do-in-drake/hello-drake and encountered the error below.

Upon running command "bazel run //examples/hello:hello_exe", the error occurred:

ERROR: /Users/wong_imacpro/Programs/drake/examples/hello/BUILD.bazel:6:16: no such target '//common:text_logging_gflags': target 'text_logging_gflags' not declared in package 'common' (did you mean 'add_text_logging_gflags'?) defined by /Users/wong_imacpro/Programs/drake/common/BUILD.bazel and referenced by '//examples/hello:hello_exe'
ERROR: Analysis of target '//examples/hello:hello_exe' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.234s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)

I built drake from source obtained at git@github.com:RobotLocomotion/drake.git.  
My system.. MacOS Big Sur V11.2.3 ... I searched but couldn't find anything relating to this issue. Thanks

**Comment by guzhaoyuan** [comment]
Sorry I don't have a Mac and cannot help with macOS. The best way to ask for help is to open an issue in Github Drake.
